### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by abenedetti1968** [fredclausen/Buster-Docker-Fixes#6]
Below the error:

raspberrypi:~ $ curl -sL https://raw.githubusercontent.com/sdr-enthusiasts/Buster-Docker-Fixes/main/libseccomp2-checker.sh | bash
Welcome to the libseccomp2 upgrade script for Debian Stretch and Buster. This script is meant to be run on Raspberry Pi Buster/Stretch-based systems that have Docker containers
that run Debian Bullseye or later. For this, the "libseccomp2" library version must be 2.4 or later.
This script will check this, and upgrade the library as necessary.

Once upgraded, you can always stay up to date by typing "sudo apt update && sudo apt upgrade" on your command line.

Your system is "BUSTER" based, and it has libseccomp2 v2.3. Upgrade is recommended.
We will first update your system with the latest package versions. Please be patient, this may take a while.
Press ENTER to the upgrade or Control-C to cancel

Scaricamento di:1 http://deb.debian.org/debian buster-backports InRelease [51,4 kB]
Scaricamento di:2 http://httpredir.debian.org/debian buster-backports InRelease [51,4 kB]
Trovato:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
Trovato:4 http://archive.raspberrypi.org/debian buster InRelease
Scaricamento di:5 http://giteduberger.fr rpimonitor/ InRelease [1.933 B]
Trovato:6 https://download.docker.com/linux/raspbian buster InRelease
Ignorato:1 http://deb.debian.org/debian buster-backports InRelease
Errore:2 http://httpredir.debian.org/debian buster-backports InRelease
  Le seguenti firme non sono state verificate perché la chiave pubblica non è disponibile: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Lettura elenco dei pacchetti...
W: Errore GPG: http://deb.debian.org/debian buster-backports InRelease: Le seguenti firme non sono state verificate perché la chiave pubblica non è disponibile: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
W: Errore GPG: http://httpredir.debian.org/debian buster-backports InRelease: Le seguenti firme non sono state verificate perché la chiave pubblica non è disponibile: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: Il repository "http://httpredir.debian.org/debian buster-backports InRelease" non è firmato.

Now upgrading libseccomp2...
Executing: /tmp/apt-key-gpghome.E5QaS7sVBS/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.E5QaS7sVBS/S.dirmngr' failed: IPC connect call failed
gpg: ricezione dal keyserver fallita: No dirmngr
[ERROR] Error in line 80 when executing: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138. Please fix the issue and run the script again.
pi@raspberrypi:~ $       

Many thanks

**Comment by kx1t** [comment]
Your Apt Keys are out of date - this is not a script error, but a configuration issue of your machine.

You can try fixing it like this:
```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6ED0E7B82643E131
```
Then run the script again

If that works, feel free to close this issue.

Please note that we don't actively support Buster based systems anymore. That means - it should work, but we'll only give a limited amount of attention to this. We recommend upgrading your Raspberry Pi OS to Bullseye, or even better, to Bookworm. This can be done with `sudo apt full-upgrade` (warning! warning! danger! danger! - this may or may not work, and it may leave your system in an unworkable state - do at your own risk!), or, even better, by simply flashing a new version of the OS onto a SDR card; we recommend DietPi but Raspberry Pi OS will work too.

**Comment by abenedetti1968** [comment]
Many thanks I will update. In the meanwhile I obtain this error:

pi@raspberrypi:/etc/apt/sources.list.d $ sudo apt-key adv --keyserver http://keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
Executing: /tmp/apt-key-gpghome.KRAiYfIC6O/gpg.1.sh --keyserver http://keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9
gpg: Non sono stati trovati dati OpenPGP validi.
gpg: Numero totale esaminato: 0
pi@raspberrypi:/etc/apt/sources.list.d $ sudo apt-key adv --keyserver http://keyserver.ubuntu.com --recv-keys 6ED0E7B82643E131
Executing: /tmp/apt-key-gpghome.ttZUJhQkar/gpg.1.sh --keyserver http://keyserver.ubuntu.com --recv-keys 6ED0E7B82643E131
gpg: Non sono stati trovati dati OpenPGP validi.
gpg: Numero totale esaminato: 0
pi@raspberrypi:/etc/apt/sources.list.d $   
 
I really appreciate if you can help me.

Many thanks.

**Comment by kx1t** [comment]
I did some more digging -- try this one? I am not sure if it will work, I found it [here](https://discuss.freedombox.org/t/solved-buster-backports-public-key-is-not-available-raspberry-pi-1b/327/2):
```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
```

**Comment by abenedetti1968** [comment]
Many thanks. Unfortunately the result is the same:

pi@raspberrypi:~ $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
Executing: /tmp/apt-key-gpghome.ihS9063k3W/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
gpg: key E0B11894F66AEC98: public key "Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>" imported
gpg: Numero totale esaminato: 1
gpg:              importate: 1
pi@raspberrypi:~ $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
Executing: /tmp/apt-key-gpghome.kELKfSAjP9/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
gpg: key DC30D7C23CBBABEE: public key "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" imported
gpg: Numero totale esaminato: 1
gpg:              importate: 1
pi@raspberrypi:~ $ curl -sL https://raw.githubusercontent.com/sdr-enthusiasts/Buster-Docker-Fixes/main/libseccomp2-checker.sh | bash
Welcome to the libseccomp2 upgrade script for Debian Stretch and Buster. This script is meant to be run on Raspberry Pi Buster/Stretch-based systems that have Docker containers
that run Debian Bullseye or later. For this, the "libseccomp2" library version must be 2.4 or later.
This script will check this, and upgrade the library as necessary.

Once upgraded, you can always stay up to date by typing "sudo apt update && sudo apt upgrade" on your command line.

Your system is "BUSTER" based, and it has libseccomp2 v2.3. Upgrade is recommended.
We will first update your system with the latest package versions. Please be patient, this may take a while.
Press ENTER to the upgrade or Control-C to cancel

Scaricamento di:1 http://deb.debian.org/debian buster-backports InRelease [51,4 kB]
Trovato:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Trovato:4 http://archive.raspberrypi.org/debian buster InRelease
Ignorato:3 http://giteduberger.fr rpimonitor/ InRelease
Errore:5 http://giteduberger.fr rpimonitor/ Release
  Redirection loop encountered
Errore:1 http://deb.debian.org/debian buster-backports InRelease
  Le seguenti firme non sono state verificate perché la chiave pubblica non è disponibile: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Lettura elenco dei pacchetti...
E: Il repository "http://giteduberger.fr rpimonitor/ Release" non ha più un file Release.
W: Errore GPG: http://deb.debian.org/debian buster-backports InRelease: Le seguenti firme non sono state verificate perché la chiave pubblica non è disponibile: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: Il repository "http://deb.debian.org/debian buster-backports InRelease" non è firmato.

Now upgrading libseccomp2...
Executing: /tmp/apt-key-gpghome.P2Wrxqh4kA/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
gpg: key DC30D7C23CBBABEE: "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" not changed
gpg: key E0B11894F66AEC98: "Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>" not changed
gpg: Numero totale esaminato: 2
gpg:         non modificate: 2
deb [trusted=yes] http://deb.debian.org/debian buster-backports main
E: Impostati valori in conflitto per l'opzione Trusted riguardo alla sorgente http://deb.debian.org/debian/ buster-backports
E: Impossibile leggere l'elenco dei sorgenti.
[ERROR] Error in line 83 when executing: sudo apt update. Please fix the issue and run the script again.
pi@raspberrypi:~ $ A

**Comment by abenedetti1968** [comment]
Solved. 

# Get signing keys to verify the new packages, otherwise they will not install
rpi ~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138

# Add the Buster backport repository to apt sources.list
rpi ~$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list

rpi ~$ sudo apt update
rpi ~$ sudo apt install libseccomp2 -t buster-backports

from   [https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/?source=post_page-----fbde9574cad8--------------------------------](url)

**Comment by abenedetti1968** [comment]
many thanks

**Comment by kx1t** [comment]
:) Glad to see - happy holidays!
